### ISSUE TITLE
Unhelpful Error Output

### ISSUE THREAD

**Issue by markciecior** [grafana/django-saml2-auth#103]
I'm trying to replace the fangli library with this one, but cannot see anything but a generic "Sorry, you are not allowed to access this app" error - no error code is specified.  I'm using Duo as my SAML IdP.

I cannot get a log file to generate, despite enabling the DEBUG setting.

A stack trace shows [this line](https://github.com/IdentityPython/pysaml2/blob/d3aeeabcd1dfcf224b0c224fe3e2f5b8c0202940/src/saml2/client_base.py#L449) as the last path before handling the exception.

How can I get more info to continue troubleshooting this problem?

**Comment by mostafa** [comment]
Hey @markciecior,

Can you give me your configuration or code snippets? Please exclude sensitive information.

**Comment by markciecior** [comment]
Hi @mostafa,

I finally got my logging working properly.  Here is my settings value:

```
SAML2_AUTH = {
    'METADATA_AUTO_CONF_URL': 'https://sso-abcd1234.sso.duosecurity.com/saml2/sp/ABC123XYZ/metadata',
    'DEBUG': True,
}
```
I obfuscated the URL a bit, but the real one returns SAML/XML output, including a cert signed by Duo's public CA.

The HTML error page is unhelpful because there is no value for the `error_code` or `reason` variables in the `django_saml2_auth/error.html` template.  But when you look past those `VariableDoesNotExist` exceptions, here is what's failing:

```
Traceback (most recent call last):
  File "/code/cait_tools/.venv/lib/python3.9/site-packages/django_saml2_auth/utils.py", line 179, in wrapper
    result = function(request)
  File "/code/cait_tools/.venv/lib/python3.9/site-packages/django_saml2_auth/views.py", line 272, in signin
    _, info = saml_client.prepare_for_authenticate(relay_state=next_url)  # type: ignore
  File "/code/cait_tools/.venv/lib/python3.9/site-packages/saml2/client.py", line 71, in prepare_for_authenticate
    reqid, negotiated_binding, info = self.prepare_for_negotiated_authenticate(
  File "/code/cait_tools/.venv/lib/python3.9/site-packages/saml2/client.py", line 157, in prepare_for_negotiated_authenticate
    reqid, request = self.create_authn_request(
  File "/code/cait_tools/.venv/lib/python3.9/site-packages/saml2/client_base.py", line 481, in create_authn_request
    msg = self._message(
  File "/code/cait_tools/.venv/lib/python3.9/site-packages/saml2/entity.py", line 605, in _message
    signed_req = self.sign(
  File "/code/cait_tools/.venv/lib/python3.9/site-packages/saml2/entity.py", line 541, in sign
    return signed_instance_factory(msg, self.sec, to_sign)
  File "/code/cait_tools/.venv/lib/python3.9/site-packages/saml2/sigver.py", line 338, in signed_instance_factory
    signed_xml = seccont.sign_statement(
  File "/code/cait_tools/.venv/lib/python3.9/site-packages/saml2/sigver.py", line 1722, in sign_statement
    return self.crypto.sign_statement(
  File "/code/cait_tools/.venv/lib/python3.9/site-packages/saml2/sigver.py", line 806, in sign_statement
    (stdout, stderr, output) = self._run_xmlsec(com_list, [tmp.name])
  File "/code/cait_tools/.venv/lib/python3.9/site-packages/saml2/sigver.py", line 869, in _run_xmlsec
    logger.debug('xmlsec command: %s', ' '.join(com_list))
TypeError: sequence item 3: expected str instance, NoneType found
```

The value of com_list at this time is:

`['/usr/bin/xmlsec1', '--sign', '--privkey-pem', None, '--id-attr:ID', 'urn:oasis:names:tc:SAML:2.0:protocol:AuthnRequest', '--node-id', 'id-ABCXYZ123456', '--output', '/tmp/tmpj8snbkax.xml', '/tmp/tmp6khb5olb.xml']`

It seems the `key_file` name is not specified, defaulting to `None`, causing the error.

The logic flaw appears to be [here](https://github.com/IdentityPython/pysaml2/blob/964e885054d9f0ac8e228267e194d183f93c34e0/src/saml2/sigver.py#L1670).  What I don't understand is, where is the key _supposed_ to come from?

**Comment by mostafa** [comment]
@markciecior 
The library doesn't support encryption at the moment. It only supports signing with the provided certificate in the SAML metadata file.

**Comment by ihabzee** [comment]
@mostafa is there an estimate of when this issue could be resolved? I am facing the same problem.

**Comment by 73VW** [comment]
Hey, sorry to reopen this thread but I seem to get the same error.

Anyone managed to find a workaround for this?

**Comment by 73VW** [comment]
Note for anyone coming here:

`CERT_FILE` and `KEY_FILE` have nothing to do with your DUO configuration.

They are a private key and a public cert that YOU generate.
You can do it this way:

``` bash
openssl genpkey -algorithm RSA -out private.key -pkeyopt rsa_keygen_bits:4096
openssl req -new -x509 -key private.key -out public.crt
```
